version: 2

jobs:
  cross:
    steps:
      - checkout
      - run: apk add make curl
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl -fsSL --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/${BUILDX_VERSION}/buildx-${BUILDX_VERSION}.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker buildx version
      - run: docker context create buildctx
      - run: docker buildx create --use buildctx && docker buildx inspect --bootstrap

workflows:
  version: 2
  ci:
    jobs:
      - cross
